/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.8.3/userguide/multi_project_builds.html
 *
 * This project provides a Java implementation of base45.
 */

import de.fayard.refreshVersions.bootstrapRefreshVersions

// For more information on how this works, see
// https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_management
pluginManagement { //  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
    plugins {
        id("com.github.spotbugs") // spotbugs plugin
    } // end plugins

    resolutionStrategy {
        // intentionally empty
    } // end resolutionStrategy

    // Note 1: Although section "dependencyResolutionManagement" contain these repositories
    //         it is necessary to specify them here as well. Otherwise build fails.
    repositories {
        gradlePluginPortal()
    } // end repositories
} // end pluginManagement section __________________________________________________________________

dependencyResolutionManagement { //  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
    repositories {
        gradlePluginPortal()
        mavenCentral()
    } // end repositories
} // end dependencyResolutionManagement ____________________________________________________________

// For setting up refreshVersions plugin see
// https://jmfayard.github.io/refreshVersions/
buildscript { // . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
    // Note 2: Although block "dependencyResolutionManagement" in settings.gradle.kts
    //         covers "gradlePluginPortal" this repositories-block is necessary here.
    //         Otherwise build fails.
    repositories {
        gradlePluginPortal()
    }
    dependencies.classpath("de.fayard.refreshVersions:refreshVersions:0.9.7")
} // end buildScript section _______________________________________________________________________

bootstrapRefreshVersions()

rootProject.name = "base45"
include("lib")
